#! /bin/sh

# /etc/rcS.d/15inetd
#
# Start our network services daemon

mkdir -p /var/lock/subsys/network
#[ -f /var/lock/subsys/network ] || exit 0

echo "Starting INET services...."
inetd
touch /var/lock/subsys/inetd

exit 0
